# Generated by Django 4.2.6 on 2023-10-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sml", "0002_alter_urldata_short_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="urldata",
            name="name",
            field=models.TextField(default=None, max_length=25),
        ),
    ]
